### ISSUE TITLE
the contents of a shared folder cannot be seen

### ISSUE THREAD

**Issue by morsaus** [cguZZman/script.module.clouddrive.common#17]
in "shared with me" I don't see a shared folder that is visible from other applications or browsers.  in other cases some folders are visible but subfolders are not listed

**Comment by cguZZman** [comment]
Not sure what you're referring about.
That's why the template for the issue was there before you ignored it.

**Comment by morsaus** [comment]
if there is an intention to improve, I could try to explain the problem better.

**Comment by morsaus** [comment]
> Not sure what you're referring about.
> That's why the template for the issue was there before you ignored it.

if there is an intention to improve, I could try to explain the problem better.
